### ISSUE TITLE
[docs] guide/use: show framework examples  

### ISSUE THREAD

**Issue by ARuzek** [lit/lit-element#1041]
## Description
- Who wants the functionality: **beginners / jr developers**
- What it is they want: **framework specific "use a web component" guide for Angular, React, Vue, etc...** 
- Why they want it: **Large enterprises are using web components not on their own, but to bridge multiple development teams on multiple existing frameworks. Those unfamiliar with web components need it spelled out to see how easy it is to implement within their existing framework. Making it obvious will push faster adoption.**
- Functional description of task/subtask: **Create a code snippet for each of the major frameworks to show that Lit-Element is not in competition, but rather works nicely within an existing framework ecosystem.** 

## Acceptance criteria
Complete if a new jr developer can scroll to their framework and see an example within a framework that they are familiar with. Nice to have: if they can see where using the WC would fit into their existing file structure scaffold.

**Comment by sorvell** [comment]
Thanks for posting this issue. We definitely agree this is pretty important to add to our documentation. Web components work everywhere. This is their main value proposition. Showing that they work well in web frameworks is an important piece of that vision.

**Comment by justinfagnani** [comment]
We have tasks to track this in the https://github.com/lit/lit.dev repo, and we have React docs in a Frameworks section.
