### ISSUE TITLE
Why lit-element not support babel  decorators plugin use legacy

### ISSUE THREAD

**Issue by WUSO01** [lit/lit-element#1140]
Use `['@babel/plugin-proposal-decorators', { legacy: true }]` , the `@query` return `undefined` and the`updated(changedProperties)` return nothing. Maybe other problems I didn't find

I know there is no problem  using `decoratorsBeforeExport`.

links: #1138 , #1121

**Comment by sorvell** [comment]
Thanks for the PR on this. If we can get testing setup for Babel legacy decorators, we can merge this.

**Comment by sorvell** [comment]
Closing as current support is documented at: https://lit.dev/docs/components/decorators/#enabling-decorators.
