### ISSUE TITLE
Enable GitHub discussions?

### ISSUE THREAD

**Issue by tony** [lit/lit-element#1151]
## Description
- Who wants the functionality

  #245, #239 - issues relating to implementation that were closed, but I think would have been valuable to continue

  So far just me? I'm having a difficult time tracking down complex examples of LitElement

  `site:https://github.com/Polymer "discussions"` doesn't show up much, so I think this _may_ be the first time it's been brought up
- What it is they want

  A place to direct implementation / execution related questions about LitElement, separate from GH issues

  To continue good questions unsuitable as a normal issues
- Why they want it

  - To complement LitElement's excellent documentation
  - Exchange implementation ideas / examples: Specifically about LitElement
  - Environment configuration/troubleshooting, building and integrating LitElement
    
    As someone totally new to the library, the documentation on the project is amazing, but the execution can be really hard.

    My habits from working on web frameworks / my current flow didn't translate over.
  
    I had to go through a few hurdles to finally get LitElement working that weren't covered in the docs:

    - tsconfig and babel
    - build systems like webpack
    - dev server 
    - styling
    - importing web component itself
    - wiring in third party libraries
    - typescript edgecases

    There was a lot of troubleshooting I had to do to get it working that spanned across days. I think it's expected that those of us with a lot of investment with frameworks/build systems need a place to specifically discuss this project
  - Closer to the issue tracker / codebase than StackOverflow
  - Easier to cite issues and code without leaving GH
- Functional description of task/subtask
  - Enabling discussions and trying it out
  - Forward issues unrelated to project development / implementation related (e.g. #245 #239) to discussions instead of closing

## Acceptance criteria

I think this would be up to the Polymer team if they wanted to experiment with GH Discussions.

StackOverflow and other sites exists. There'd need to be curiosity / interest in trying out discussions.  The #1 value I can think of would be moving QA-related issues to discussions. Since those come up on Google/GH Search

Any thoughts on this?

**Comment by kevinpschaaf** [comment]
Closing as discussions are now open at https://github.com/lit/lit/discussions
