### ISSUE TITLE
Typescript error on latest build

### ISSUE THREAD

**Issue by markcellus** [lit/lit-element#1179]
### Description
There appears to be a TS error on [this line](https://github.com/Polymer/lit-element/blob/b212f87e264a4db0ea571c141eb77935a008201a/src/lib/updating-element.ts#L526) when building lit-element with latest Typescript version.

#### Expected Results
No TS error

#### Actual Results
TS Error (see attachment below)
![image](https://user-images.githubusercontent.com/1446916/112991779-82e0d900-9135-11eb-89f7-965275c310a1.png)

### Versions

- typescript: 4.2.3
- lit-element: v2.4.0
- webcomponents: vX.X.X

**Comment by kevinpschaaf** [comment]
Closing due to age; please reopen if issue persists on latest versions.
