### ISSUE TITLE
Persistance?

### ISSUE THREAD

**Issue by tamis-laan** [lit/lit-element#1185]
Would be nice to have some established way to persist component state! Any recommendations for now?

**Comment by christophe-g** [comment]
I am using https://github.com/gitaarik/lit-state, synchronizing with firebase or localStorage

**Comment by kevinpschaaf** [comment]
While an interesting feature, this is out of scope for the core Lit library.

**Comment by sorvell** [comment]
Closing based on the previous suggestion. This is out of scope for the core library. You may want to investigate [service workers](https://developers.google.com/web/fundamentals/primers/service-workers).

**Comment by justinfagnani** [comment]
The question could be referring to using local storage, or a state management system like Redux. It would be interesting to think of if there's a nice use for reactive controllers to access local storage.

**Comment by christophe-g** [comment]
> It would be interesting to think of if there's a nice use for reactive controllers to access local storage.

Thought about the same : https://github.com/gitaarik/lit-state/issues/7#issue-867696705
