### ISSUE TITLE
state() is shown as deprecated in LitElement 2.5

### ISSUE THREAD

**Issue by Artur-** [lit/lit-element#1191]
## Description
```
@customElement('chat-view')
export class ChatView extends View {
  @state()
  private items: ChatItem[] = [];
```

This is shown in VS Code as
![image](https://user-images.githubusercontent.com/260340/117005484-facf8f80-acef-11eb-96cc-aa5ae5baccdf.png)

**Comment by justinfagnani** [comment]
Oops! That's what happens when you copy and paste `internalProperty()` 😬
