### ISSUE TITLE
Git tags are not in sync with npm tags

### ISSUE THREAD

**Issue by elycruz** [lit/lit-element#1200]
### Description:
Same as title.

### Acceptance criteria
Git tags are updated as part of "deploy to npm" process on every release.

**Comment by justinfagnani** [comment]
In the lit monorepo we're going to set up tooling to automate this. In this repo we need to manually update the tags. We don't expect a lot of release to be made from here going forward.

**Comment by elycruz** [comment]
Ok, gotcha.  Thanks for reply - Also, I noticed I had added the issue to the 2.x branch after the fact (lol - had meant to change it before the end of the week (but you know how that could sometimes go (lol)) - Will repost the issue in the 3.x monorepo (as I see the issue there too).
