### ISSUE TITLE
No release major/minor branches available for reference.

### ISSUE THREAD

**Issue by elycruz** [lit/lit-element#1201]
#### Who 
This benefits everyone involved with the repos: users, maintainers/developers etc.

#### What 
Branches that correspond to trailing "major" releases where all patches/minor updates for those releases could be found;  E.g.
Example branches:
- `1.x.x`
- `2.x.x`
- etc.

*Note:* With this additional approach the 'main' branch is occupied by the latest "major" release (and it's patches etc.).

##### Additional reasoning
Managing release branches is not a fun thing to do, and I admit, is extra work however with new development paradigms/approaches coming up all the time, in the frontend world, troubleshooting becomes a thing that more and more people have perform on their respective projects.  Having these release branches would offer us an additional way to inspect different release sets directly from a branch.  *However*, if release tagging (#1200 ) is kept in sync with releases made to npm this ticket is unnecessary.

#### Why
This allows users to be able to quickly see how things work in a specific major release without having to wade through all the listed branches, change commits etc..

- Functional description of task/subtask
Create a branch for all trailing "major" releases where all patches can be merged into/maintained.

## Acceptance criteria
A branch is created for the 2.x.x version line of the library where all it's minor, and patch, updates are kept.

**Comment by justinfagnani** [comment]
This entire repo is the 2.x line. All 3.x work is done in the lit/lit monorepo.

**Comment by elycruz** [comment]
👍🏽.  Thanks, will keep this in mind in the future.
