### ISSUE TITLE
Accessibility => lit-element + Google Chrome Screen Reader  Extension => UI Design is Changed

### ISSUE THREAD

**Issue by VijayanRamachandran** [lit/lit-element#1204]
Hi,

We are facing a problem related to Accessibility topic for LitElement control in combination with Google Chrome Screen Reader Extension. 

Below, a quick sample WebComponent ( abc-toggle.js ) created using LitElement and hosted in chrome.

**abc-toggle.js**

![image](https://user-images.githubusercontent.com/25306014/125735960-829b6139-d318-4003-adb6-f562fef46771.png)

Until enabling chrome screen reader everything works as expected...

**Google Chrome Screen Reader** => https://chrome.google.com/webstore/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn?hl=en

**Before enabling chrome screen reader**

The above WebComponent is displayed in HTML page as below

![image](https://user-images.githubusercontent.com/25306014/125737129-42846f07-17cb-4c0c-9ef9-90fe2fc91d7f.png)

**After enabling Chrome Screen Reader**

For accessibility purpose after enabling the extension, the above WebComponent is displayed in HTML page as below

![image](https://user-images.githubusercontent.com/25306014/125737412-0bacfdb7-ad88-4548-b788-a26b35080d0c.png)

**Without Chrome Screen Reader**

**DOM Structure**

![image](https://user-images.githubusercontent.com/25306014/125737618-d3e19aa9-dbd6-4be3-97a5-590cd0181dd0.png)

**Styles applied to div tag inside #shadow-root**

![image](https://user-images.githubusercontent.com/25306014/125737743-c1f1a579-33d5-4f78-84cd-b54bc4b76d1b.png)

**After enabling Chrome Screen Reader**

**DOM Structure**

![image](https://user-images.githubusercontent.com/25306014/125737920-c8b40b0d-9d58-4c81-b5dd-e5ce57d00a9d.png)

**Styles applied to div tag inside #shadow-root**

![image](https://user-images.githubusercontent.com/25306014/125737936-9aa39b2b-ee5c-4467-b209-f8c6083ccb85.png)

PS: 
1. Hereby below, the entire WebComponent along with package.json
   [ToogleButton.zip](https://github.com/lit/lit-element/files/6820789/ToogleButton.zip)

2. I tried hosting the same in chrome Unsafe mode and there also same problem.

Can you please help us regarding this or if there is already some information related to scenario please let me know ?

**Comment by justinfagnani** [comment]
I filed a bug with the extension here: https://bugs.chromium.org/p/chromium/issues/detail?id=1232133

But it looks like the extension is in maintenance mode and that users should use the built-in screen reader: https://support.google.com/chromebook/answer/7031755

**Comment by VijayanRamachandran** [comment]
@justinfagnani , @AndrewJakubowicz : Thanks for the help and fast response...

**Comment by AndrewJakubowicz** [comment]
Hi @VijayanRamachandran,

I made a [small patch](https://chromium.googlesource.com/chromium/src/+/08f84c2c6875876de9e165fe9720dc3b8c17f39a) to the extension that should improve the style situation. The extension still breaks parts of pages in certain difficult contexts - i.e. iframes. But from my testing it's far more reliable.

Otherwise echoing Justin that the extension is in maintenance mode.
Let me know how the updated extension works and thank you for the issue report!
