### ISSUE TITLE
Property does not re-render when fired from custom event

### ISSUE THREAD

**Issue by Siavee-uni** [lit/lit-element#1205]
Hey,
somehow, properties don't update if I fire a custom element and receive it in another component, not being the parent or the same component the event was fired from.

When I console log, the property changed. But it doesn't re-render.

Example here: https://stackblitz.com/edit/typescript-18e7yc?file=components/custom-event.ts

**Comment by kevinpschaaf** [comment]
It's pretty unclear from your code what you intend to happen, so it would be good if your bug report had "expected" and "actual" sections.

However, one thing it appears you're getting tripped up on is passing an unbound function to `addEventListener`: 

```js
    document
      .querySelector('custom-event')
      .addEventListener('custom-event', this.changeStringParent);
```

When an un-bound function is passed to `addEventListener`, the function will be called with the `this` of the event _target_, not the class instance the function was defined on.

Instead, if you want `changeStringParent` to be called on the local class, you need to pass a bound function, either using arrow syntax or `bind`, e.g.:

```js
    document
      .querySelector('custom-event')
      .addEventListener('custom-event', () => this.changeStringParent());
```

Please see this for an updated version and confirm if these results are what you intende: https://stackblitz.com/edit/typescript-ppx3bl?file=app.ts

**Comment by Siavee-uni** [comment]
Wow thanks. Yes i though `this` was referring to the class instance.

**Comment by sorvell** [comment]
It may be that you're hitting an issue addressed via the [`live` directive](https://lit.dev/docs/templates/directives/#live). Closing optimistically due to age, but please feel free to open a new issue if there is something else going on. Thanks.
