### ISSUE TITLE
Litelement Boolean property returns undefined in when not set

### ISSUE THREAD

**Issue by nchaitra** [lit/lit-element#1210]
We are using lit-element library for developing custom components. In that we are facing one issue when doing automation. 
When we are setting boolean property the value will be true when boolean is set  and undefined when removed.
This way it is different from native html button where we will get false when disabled is removed from button.

`<my-button disabled></my-button>`

when we run
document.querySelector('my-button').disabled 
This returns true since disabled is set.
In automation tool it is shown as below when disabled is set
![image](https://user-images.githubusercontent.com/77773147/136324264-a3bbf3f4-2caa-4c20-a05b-dd7b84baf678.png)

`<my-button></my-button>`
In automation tool it is shown as below when disabled is removed.

![image](https://user-images.githubusercontent.com/77773147/136324287-777148d8-33d7-4021-b31a-8316a7c9806b.png)

In this we will not see the disabled atribute itself when spying the button component.

Same issue is reported  here as well for custom components.
https://www.ranorex.info/html-unary-attributes-how-to-identify-attribute-wi-t17059.html

**Comment by nchaitra** [comment]
Property is declared like below
`  static get properties() {
    return {
      disabled: { type: Boolean, reflect: true }
    };`

**Comment by DykiSA** [comment]
I've same issue, then I just initialize it on class constructor

```javascript
constructor() {
  super();
  this.disabled = false;
}
```

**Comment by justinfagnani** [comment]
^ that's the correct solution. Lit doesn't initialize class fields, it just makes them reactive. In JavaScript a field in `undefined` until it's set.

**Comment by sorvell** [comment]
As @justinfagnani mentioned, this is expected behavior and initializing the property is the right way to address it.
