### ISSUE TITLE
Starter projects missing in getting started documentation

### ISSUE THREAD

**Issue by mangelozzi** [lit/lit-element#1215]
Goto <https://lit-element.polymer-project.org/guide/start#download-the-starter-project>
And try download:
- [LitElement JavaScript starter project](https://github.com/PolymerLabs/lit-element-starter-js)
- [LitElement TypeScript starter project](https://github.com/PolymerLabs/lit-element-starter-ts)

Both give a 404

**Comment by justinfagnani** [comment]
We mention them on lit.dev now: https://lit.dev/docs/getting-started/#lit-starter-kits

We are going to redirect lit-element.polymer-project.org to lit.dev soon which will take care of legacy content like this.

This repo is only for maintenance of LitElement 2.x. LitElement 3.x is now part of the lit/lit monorepo. Please file any new issues here: https://github.com/lit/lit/issues
