### ISSUE TITLE
How do you get the actual click event target?

### ISSUE THREAD

**Issue by treeder** [lit/lit-element#1216]
If I have this in my component called `my-component`

```html
<div @click="${this.doSomething}">click me</div>
```

And this function:

```js
 doSomething(e) {
        console.log("doSomething", e)
    }
```

`e.target` is the web component, ie: `my-component`, not the div that I would expect. How do I find the div that was clicked?

**Comment by sorvell** [comment]
The target is the div in this case. Only if an event crosses a shadowRoot target is it retargeted. In that case, `event.composedPath()` provides an array, the first element of which is the original target.

**Comment by treeder** [comment]
But it's not the div, that's the problem.

**Comment by abraham** [comment]
If you just look at the logged output in DevTools it might not show what you're expecting after the fact. You can see that target is the div in the click handler though.

[demo](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcblxuQGN1c3RvbUVsZW1lbnQoJ3NpbXBsZS1ncmVldGluZycpXG5leHBvcnQgY2xhc3MgU2ltcGxlR3JlZXRpbmcgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgc3RhdGljIHN0eWxlcyA9IGNzc2BwIHsgY29sb3I6IGJsdWUgfWA7XG5cbiAgQHByb3BlcnR5KClcbiAgbmFtZSA9ICdTb21lYm9keSc7XG5cbiAgZG9Tb21ldGhpbmcoZXZlbnQpIHtcbiAgICB0aGlzLm5hbWUgPSBldmVudC50YXJnZXQudGFnTmFtZVxuICB9XG4gIFxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgPGRpdiBAY2xpY2s9XCIke3RoaXMuZG9Tb21ldGhpbmd9XCI-SGVsbG8sICR7dGhpcy5uYW1lfSE8L2Rpdj5gO1xuICB9XG59XG4ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vc2ltcGxlLWdyZWV0aW5nLmpzXCI-PC9zY3JpcHQ-XG48L2hlYWQ-XG48Ym9keT5cbiAgPHNpbXBsZS1ncmVldGluZyBuYW1lPVwiV29ybGRcIj48L3NpbXBsZS1ncmVldGluZz5cbjwvYm9keT5cbiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4yLjAuMFwiLFxuICAgIFwiQGxpdC9yZWFjdGl2ZS1lbGVtZW50XCI6IFwiXjEuMC4wXCIsXG4gICAgXCJsaXQtZWxlbWVudFwiOiBcIl4zLjAuMFwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMi4wLjBcIlxuICB9XG59IiwiaGlkZGVuIjp0cnVlfV0)

**Comment by treeder** [comment]
Ahh, interesting. Ya, was looking at dev tools and it shows the target as the component:
