### ISSUE TITLE
[docs] Review Templates page for technical accuracy

### ISSUE THREAD

**Issue by ghost** [lit/lit-element#352]
Review the content at https://lit-element.polymer-project.org/guide/templates for technical accuracy only.

Markdown source: https://github.com/Polymer/lit-element/blob/master/docs/_guide/templates.md

* [ ] remove `static` from getters in composition example
* [ ] fix named slots code samples
* [ ] `.alert-warning` for gotchas

**Comment by frankiefu** [comment]
In [Compose a template from other templates](https://lit-element.polymer-project.org/guide/templates#compose-a-template-from-other-templates) section, the code snippet doesn't seem to work. I think you want the getters without `static` keyword.

**Comment by keanulee** [comment]
Example code under [Use named slots](https://lit-element.polymer-project.org/guide/templates#use-named-slots) don't look right

![image](https://user-images.githubusercontent.com/1319720/49903702-efc4ed80-fe1c-11e8-810a-972242ec30d4.png)

**Comment by keanulee** [comment]
"Use name, not id, to select slots."

That's seems more like a warning than actual documentation, since `id` on `<slot>` doesn't do anything special. Maybe use `.alert-warning` for gotcha things?

**Comment by sungmuk** [comment]
Hi. 

In [Compose a template from other templates section](https://lit-element.polymer-project.org/guide/templates#compose-a-template-from-other-templates)

**static get headerTemplate** 
It still does not work. Is the docs misleading?

**Comment by justinfagnani** [comment]
There's an issue with the "Design a performant template" section, around the dom-manip example and the description that the DOM manipulation is inefficient. It's actually not, but it would be overwritten by the template and in many cases direct DOM manipulation could break the template by changing part placeholder nodes.
