### ISSUE TITLE
[docs] Nuances of control over properties/changes/setting/updates/etc

### ISSUE THREAD

**Issue by ghost** [lit/lit-element#381]
From sorvell

> 
> LitElement defines accessors for A property changes whenever it's set to a different value.
> 
> For properties of non-trivial type (i.e. objects), sometimes you want more direct control over whether or not the update system sees a "set" as a change. In particular, maybe an object's key updates and this should indicate that it's different and an update should occur. This is the intended usage for which hasChanged was designed.
> 
> If you want more direct control over the setting of a property, you can implement a getter/setter and call requestUpdate(name, oldValue) in the setter when an update should occur.
> 
> If you want to take some specific custom action (that you cannot achieve in the render method) based on the set of properties that have changed, you can implement updated(changedProperties) and take action based on the entire state of the element at that time.
> 
> 

Probably need a section on "what level of control do I need over properties & how should I achieve it"

**Comment by katejeffreys** [comment]
Lifecycle

**Comment by jhnsntmthy** [comment]
Can you also add some documentation and examples to the [property].hasChanged methods that are available? The docs link to a nothing page, and there is not a real clear understanding of how to use this.

I am assuming
```
//assuming a property named 'checked'
checked.hasChanged() {
	// do something here
	return true;
}
```
is how you would add this to the class, am I wrong?

**Comment by arthurevans** [comment]
Related to: #551

**Comment by kevinpschaaf** [comment]
The new https://lit.dev/docs/components/properties/ docs have treatment on most of these topics now.
