### ISSUE TITLE
[docs] Web Components basics

### ISSUE THREAD

**Issue by ghost** [lit/lit-element#385]

**Comment by katejeffreys** [comment]
* when to use e.g. `connectedCallback` etc
* when do lit-element callbacks run in relation to Web Components ones 
* Include enough info for users who are unfamiliar with Web Components APIs to use LitElement (e.g. like Polymer docs)

**Comment by kenchris** [comment]
Maybe this is useful to link to: https://w3ctag.github.io/webcomponents-design-guidelines/

**Comment by stramel** [comment]
It would be beneficial to at least have documentation around the custom element lifecycle hooks mentioned/linked in the lifecycle section of the docs.

Maybe this? https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements#Using_the_lifecycle_callbacks

**Comment by sorvell** [comment]
Closing as this is fairly well covered at https://lit.dev/docs/components/lifecycle/.
