### ISSUE TITLE
[docs] Properties: Explain capturing instance values

### ISSUE THREAD

**Issue by ghost** [lit/lit-element#528]
>Comment on existing text. This: https://github.com/Polymer/lit-element/pull/489/files#diff-f37c02b7dd321fd8fca26553760681d7R16
>Is a little vague. I'm not sure a reader unfamiliar with upgrades and this issue already will know what that's talking about. Maybe file an issue to clean up? 

@justinfagnani FYI

**Comment by nicolejadeyee** [comment]
PR was merged and docs have been re-written. closing issue.
