### ISSUE TITLE
[docs] Publish: Add note about Babel decorators transform

### ISSUE THREAD

**Issue by ghost** [lit/lit-element#530]
In docs/_guide/publish.md

```
npm install --save-dev @babel/core
npm install --save-dev @babel/plugin-proposal-class-properties
npm install --save-dev @babel/proposal-decorators
```

justinfagnani 3 hours ago  Member
We need to add a note about this Babel decorators transform. The new decorators spec (Stage 2 decorators) are is finalized, and may change, and so might the transform. We test with version ^7.2.0 right now.

@justinfagnani  FYI

**Comment by ChALkeR** [comment]
That page also recommends `decoratorsBeforeExport: true`, but that has been accepted as `false`, ref: https://github.com/tc39/proposal-decorators/issues/69#issuecomment-455538637.

Also related: https://github.com/babel/babel/pull/9360

**Comment by kevinpschaaf** [comment]
Now covered on the lit.dev site: https://lit.dev/docs/components/decorators/#decorators-babel
