### ISSUE TITLE
[docs] Embedded code sample enhancements

### ISSUE THREAD

**Issue by ghost** [lit/lit-element#548]
Use case: 

- A code sample shows up on a page, e.g https://lit-element.polymer-project.org/
- User clicks in the code sample and it magically becomes a StackBlitz
- Samples should still be indexable somehow by search

Related:
- [ ] https://github.com/Polymer/lit-element/issues/678
- [ ] https://github.com/Polymer/lit-element/issues/550

**Comment by nicolejadeyee** [comment]
this issue is now obsolete because lit.dev now uses playground elements. closing this issue.
