### ISSUE TITLE
Canonical tsconfig

### ISSUE THREAD

**Issue by e111077** [lit/lit-element#611]
Please provide a "canonical" tsconfig.json for people to get started quicker on LitElement projects using TS. This is kinda important because, one, it helps people new to lit-element and TS, and two, it would help express how we think lit element packages should be published; specifically around import style and target javascript.

**Comment by e111077** [comment]
related #420

**Comment by fernandopasik** [comment]
Would this be a good starting point? https://github.com/material-components/material-components-web-components/blob/master/tsconfig.json

**Comment by fernandopasik** [comment]
I have a suggestion, would it make sense to set `module` to `ESNext` to support dynamic imports?

**Comment by kevinpschaaf** [comment]
Closing, as [lit-element-starter-ts](https://github.com/lit/lit-element-starter-ts) serves as our example TS setup and includes an example tsconfig.json: https://github.com/lit/lit-element-starter-ts/blob/main/tsconfig.json.
