### ISSUE TITLE
Provide release without support for non-evergreen browsers

### ISSUE THREAD

**Issue by jhpratt** [lit/lit-element#612]
A project I'm working on will only support the last 2 versions of evergreen browsers, so I don't need any features specific to IE11 or older versions. Is it possible to have a release (even a branch would suffice) that has those blocks of code removed? This will reduce the overall size of LitElement, which has consistently grown recently.

**Comment by blikblum** [comment]
Such version of lit-html would be important also

**Comment by jogibear9988** [comment]
I also think, many will provide their web apps only for the last 2 or 3 Versions of the current browsers (and no IE). Such a release would be nice!

**Comment by LarsDenBakker** [comment]
What sort of file size reduction are expecting from removing support?

**Comment by jogibear9988** [comment]
don't know, but why should I include them when not needed.
I do a big Visualization system with polymer 2 arm.
I plan to switch to lit element, and for performance matters. I've pages with over thousand custom elements, and so also small reduces in size and speed matter.

**Comment by jhpratt** [comment]
@LarsDenBakker I'm not entirely sure. I believe a nontrivial portion of lit-html/lit-element's code is to add support for browsers that don't support template elements, modern DOM APIs, and similar. As far as I know, the only thing explicitly excluded is a full WebComponents polyfill. The checks and branches for the polyfill are still present though, which aren't necessary if we know we're not using it. My browser choice certainly isn't out of the ordinary.

**Comment by jhpratt** [comment]
FWIW I recently switched away from Lit Element in favor of my own syntax and Babel plugin, in large part because of the size of this library. As a bonus, my plugin/syntax can statically determine 

If I need polyfills, that's on me to provide them. I don't believe the Lit Element should be providing them _at all_. The only thing that's happened was the removing of the performance label by someone who has extremely little activity on GitHub and appears to be in no way connected to this project officially.

After four months this issue has received no discussion whatsoever. In that time I was able to create a functional plugin that handled a large portion of what Lit Element can do, and do so at build-time rather than runtime _and_ provide for smaller files.

Is this really such a big ask? Only three issues have more +1s than this:
- (+18) Best practices, which has nothing to do with code itself
- (+13) API for slots without Shadow DOM — one of the motivations is the size of the polyfill
- (+11) Bundled JavaScript files — this is trivial to do with Rollup in CI

Of the latter two issues that would affect code, both are marked as low severity, while this is medium and at +10. If wanted, I can go through the existing code for Lit Element and roughly determine what could be cut out, giving an approximate size savings; it would be by no means exact, but would give a general idea.

On a semi-related note, why was the performance label removed? Unused code absolutely affects performance; it still needs to be parsed, compiled to machine code, and ultimately not used at all.

**Comment by justinfagnani** [comment]
@jhpratt that's great that you've been able to create your own library. That's the promise of web components in action.

We have this marked as medium priority and I hope we'll get to it, though it'll very unlikely be with a separate build, as we strongly want only one build of each of our libraries, but via a build-tool plugin that replaces some imports, like shady-render from lit-html.

**Comment by jogibear9988** [comment]
what if I use the library without a build run (as we do).
we explicitly only support new browsers (so no IE, no EDGE) and I also would like to see a minimalistic version without polyfills

**Comment by jhpratt** [comment]
@justinfagnani Surely a build tool plugin could be used to provide multiple releases automatically? I know a number of libraries already do this for ES6+ and ES5 releases (which amounts to a separate file in the dist folder).

As @jogibear9988 said, not everyone has a build step. It would be ideal to just be able to `<script type='module' src='https://yourcdn.com/lit-element'></script>` and call it a day, knowing that no unnecessary code is being included.

**Comment by justinfagnani** [comment]
The problem with multiple isn't the effort, it's the existence of the multiple builds in the first place. If one library uses one build and another library uses a different one, then you get duplication, `indexof` breaks, etc.

We strongly prefer to ship single-source-of-truth modern JS, and let applications build as needed.

**Comment by jhpratt** [comment]
> We strongly prefer to ship single-source-of-truth modern JS, and let applications build as needed.

To me, this indicates that you (at least personally) agree with my opinion that polyfills should be provided by the user of the library, no?

I'm not a huge fan of multiple builds either, but forcing a polyfill onto everyone, even when I know I won't need it, is useless at best.

There's a significant portion of Lit Element & Lit HTML that's the polyfill and checks for support. In the app I am building, I don't care about IE, which is what most (all?) of the polyfills are for. A growing number of people are no longer supporting IE, as I'm sure you're well aware.

Not to be rude, but it certainly seems like you're in the minority here. There's very much a demand for Lit Element without the polyfills present. That would obviously be a breaking change, but people seem to want it.

**Comment by LarsDenBakker** [comment]
I hope that everyone appreciates the fact that we're discussing reducing the size of a fully featured library like lit-element from 6.8kb to ~6-5kb. That's quite a milestone in front-end development :)

Perhaps a separate 'register' module which can be imported by an application which needs to support legacy browsers, and just registers/overwrites hooks in LitELement to use things like shady render. You can use that without build tools as well. This can also be useful when creating multiple outputs of an application with different browser targets.

**Comment by jogibear9988** [comment]
> We strongly prefer to ship single-source-of-truth modern JS, and let applications build as needed.

If we should use a build step everytime, why was "ES6 import" support natively implemented in the browser? I firstly used polymer, cause of not requireing a build step.

**Comment by hyperpress** [comment]
When did Polymer not require a build step?

**Comment by jogibear9988** [comment]
polymer2 ?
never I think

polymer3 ?
none if you use the polymer webserver (or our own wich also rewrites the imports).

also in electron you could use a custom protocol handler so you could directly load non relative es6 imports.

**Comment by hyperpress** [comment]
Polymer 2 relied on polymer-cli and it's tools to build it. Polymer 3 as
well.

LitElement has like 0.5 kb worth of checking code, which prevents having to
add it to the polyfills, but those checks mainly degrade gracefully like in
the case of Constructable Stylesheets, etc.

I don't disagree that what you want is where we're all headed, but as
someone who isn't building for IE11 I'm not worried about the state of the
release. We'll get there.

**Comment by jogibear9988** [comment]
if you used polymer2 in chrome, you don‘t needed a build step for your app.
we never used it.

**Comment by LarsDenBakker** [comment]
Import maps are already behind a flag in chrome, with that you dont require a build step either. 

You can use shims polyfills for import maps on older browser just like you had polyfill html imports

**Comment by hyperpress** [comment]
Yes, you can do it, but aside from intranet or electron or snap apps, I don't yet think I'd want to go to production without accounting for how many bytes I'd be pushing to a screen just to not use roll-up and Babel to optimize it . I know we're close, but I wouldn't recommend running without a build step in all but edge cases right now. Just my thoughts, and you know where that can lead to 🤯

**Comment by jogibear9988** [comment]
Yes, but you see, it depends on the use case.

So it would be nice, if somemone would like to support IE10 or others, he could include the polyfils, but it is no must.

**Comment by CaptainCodeman** [comment]
For everyone thinking that import maps are some panacea that will solve world hunger or at least mean "no build", I think you may have to prepare for some disappointment. If you are loading lots of little files, and it's a cascade of dependencies, then the latency will quickly add up and make things s-l-o-w.

Yes, I know, "http/2 server push all the thingz!" ... so now you need more hosting support and, well, a build step to generate all the manifests or whatever is going to decide what to push. Oh, and you've figured out how to not _over push_ using Cache Aware Server Push (CASPer) ... right?

Bottom line: I don't think import maps are going to solve much other than for little demo examples. Beyond that you are going to be much better off having a build and even with import maps, you still have a build step to generate them whether you want to admit it's a "build" or not.

A decent build is really not complicated and takes a minuscule amount of time to run but you can still _pretend_ you don't have one during development by making the build happen as server middleware instead.

I don't want to have my production app loading 101 copies of Google's / Polymer's copyright notice, a bundled app is always going to win.

Back to the subject ... it's best practice to NOT include polyfills, there's a comprehensive article about it here:
https://www.w3.org/2001/tag/doc/polyfills/

**Comment by jogibear9988** [comment]
yes, but for example I don‘t want a build to be needed during development.
And a build is not always as easy or fast. In our solution a build using the polymer-cli taks about 25minutes.

**Comment by jogibear9988** [comment]
And how do I do a build if I load customer modules wich are not build (cause we have only one release for all customers) and this modules also es6 import files removed in the build...

**Comment by CaptainCodeman** [comment]
> And a build is not always as easy or fast. In our solution a build using the polymer-cli taks about 25minutes.

A 25 minute build means something is _seriously_ wrong IMO. Polymer CLI isn't a great example as it rarely seemed fast but I don't think a faulty build process is a legitimate argument against builds. "I have a car that won't go, therefore cars don't work" is faulty logic.

> how do I do a build if I load customer modules wich are not build

A build doesn't mean you _can't_ still import things that you don't want to include in the build. As I said, you can just do the bare import specifier transforms using middleware during development to pretend there is no build.

Personally, I think it's a mistake and it's far better to have a consistent process during development and deployment. Typically, you don't do the full process for development, leaving minification for example to staging and production use, but it helps if you can run the exact same code that you'll be deploying in the exact same way locally.

**Comment by jhpratt** [comment]
Any updates on this? The issue has been open for over a year.

**Comment by jhpratt** [comment]
Ping @justinfagnani for an update.

**Comment by kevinpschaaf** [comment]
Closing, as a major feature of Lit 2 was moving virtually all non-evergreen support into a separate `polyfill-support` module. Read more in https://lit.dev/docs/tools/requirements/#polyfills.
