### ISSUE TITLE
Apply cssResult to instance of an element

### ISSUE THREAD

**Issue by bennypowers** [lit/lit-element#632]
### Description
I'd like to be able to apply a cssResult to an instance of an element, not to the class. An example use case would be dynamic css with `unsafeCSS`

```js
// imaginary API
this.applyStyleResult(css`${unsafeCSS(this.generateSomeDynamicStyles())}`);
```

Slack reference:  https://polymer.slack.com/archives/C03PF4L4L/p1552653870035900

**Comment by kevinpschaaf** [comment]
Just noting that the main issue with this would be polyfilled Shadow DOM support, since ShadyCSS currently does not have good support for generic instance-time styling.

**Comment by sorvell** [comment]
Closing in favor of https://github.com/lit/lit/issues/3010.
