### ISSUE TITLE
Changelog should link to changed code not issues

### ISSUE THREAD

**Issue by daKmoR** [lit/lit-element#634]
hey,

so when upgrading and something breaks then the changelog is the first thing I go to.
If something sounds like it could introduce the bug I click on details.

#### Expected Results
With the click on details, I would like to see the changed code (via PR).

#### Actual Results
With the click on details you go to the issue and there you need to search for the PR and only then do you see the changed code.

#### Sugguestion

My suggestion is to change it to link to the PR instead as it saves you time and effort.

pretty please :hugs: 

PS: if agreed upon I could prepare a PR for it :muscle:

**Comment by kevinpschaaf** [comment]
The changesets-powered changelogs for releases now reference PRs and commits: https://github.com/lit/lit/releases
