### ISSUE TITLE
unit testing

### ISSUE THREAD

**Issue by engiNisha** [lit/lit-element#652]
how to unit test the element?
please suggest the right way to do that with all mock methods with complex component

**Comment by daKmoR** [comment]
hey, for unit testing I wrote a "little" article that should give you all the right ideas
https://dev.to/open-wc/testing-workflow-for-web-components-g73

it uses https://open-wc.org/testing :muscle: 

PS: disclaimer - I am a maintainer of `@open-wc`

**Comment by engiNisha** [comment]
Thanks for quick reply. its a really nice document.One thing I just wanted to know your view about lit-element-tester  what is the difference between these two.Again one thing is the lit element app starter is using web component tester so again i am confused what to use.

**Comment by web-padawan** [comment]
The `web-component-tester`, aka WCT, was needed previously, as it was the only test runner able to handle HTML Imports easily. Now when we use ES modules in lit-element, it enables us to choose between any mainstream developer tools, including test runners like Karma.

The downsides of WCT are that it has quite a lot dependencies - in particular, it downloads SauceConnect library, which is about 10 Mb, each time you run fresh `npm install`.

Also, as of today it looks like WCT is not actively maintained, at least there doesn't seem to be any progress towards (potentially more lightweight) 7.0.0 version discussed some time ago.

**Comment by engiNisha** [comment]
Thanks for the answer . One thing I just wanted to know your view about lit-element-tester.

**Comment by web-padawan** [comment]
If you mean [lit-element-tester](https://github.com/drochgenius/lit-element-tester), to me it looks like it is based on the headless Chrome, and it doesn't say anything about testing on other browsers.

I strongly recommend anyone to test also on Firefox, which is easy to set up in CI environments like Travis or Circle CI, without need to have a SauceLabs or BrowserStack account. And if you have one, testing on Safari and iOS would be also very beneficial for the project.

We shouldn't stick to Chrome as the only engine we test our code against, that's the point. With Karma, there are launchers for any browser, including IE11 (which you can setup on AppVeyor).

**Comment by bzitzow** [comment]
We're having a discussion at work right now about applying Martin Fowler's test pyramid to web components.

It would *seem* that most tests are either component or integration tests, as at the very least a DOM integration is needed, plus the integration with lit-element, to test a component.

If a function is just pure business logic and doesn't need a component instantiation, we're moving it out of the element and into a plain javascript file (that can be unit tested directly) and the element can import that behavior.

This seems to be working well.

**Comment by rjsteinert** [comment]
@daKmoR Great work on open-wc. Reading the fixture helper helped me figure out how to make tests work in a polymer-cli generated element project. Also, I would definitely recommend the open-wc [lit demos](https://github.com/open-wc/lit-demos) as a must read for understanding Lit Element.

**Comment by jarrodek** [comment]
Are there plans to support Sauce Labs as well?

**Comment by ashubham** [comment]
Is there any guidance here ? Has anyone tried unit testing the LitElement components ? @katejeffreys

**Comment by Westbrook** [comment]
@ashubham please check the suggestion in https://github.com/Polymer/lit-element/issues/652#issuecomment-483124038... I've had great luck with the approach therein.

**Comment by aomarks** [comment]
Closing as we now have a more complete docs page about testing: https://lit.dev/docs/tools/testing/

**Comment by codingjoe** [comment]
I would greatly appreciate it if an example of a unit test written in a common test framework was included. I think this would be especially useful for those who are new to Lit and are looking for guidance on how to write unit tests in this framework. An example might provide a valuable reference and can help to illustrate key concepts and best practices.

**Comment by justinfagnani** [comment]
@codingjoe this repository isn't used for development anymore. Please use our monorepo: [lit/lit](https://github.com/lit/lit) or  docs repo: [lit/lit.dev](https://github.com/lit/lit.dev).

We have a testing page on lit.dev: https://lit.dev/docs/tools/testing/

Hopefully that has info you need. Lit is just a JavaScript library, so we should work with any test framework that supports running browsers.

**Comment by codingjoe** [comment]
Thanks @justinfagnani this just popped up on my Google search. I'll try to extend the page a little if you don't mind. There isn't a thing as too much documentation, is there ;)
