### ISSUE TITLE
[feature request] First rendered/updated hook as a promise

### ISSUE THREAD

**Issue by LarsDenBakker** [lit/lit-element#660]
Currently `firstUpdated` exists as a lifecycle callback only. It would be useful to have some hook which you can await to know that at least the dom has rendered once. For example:

```
class MyElement extends LitElement {
  set foo(newFoo) {
    this._foo = newFoo;
  
    // wait until dom is at least rendered once
    await this.firstRendered;
    this.shadowRoot.getElementById('myButton').focus();
  }

  get foo() {
    return this._foo;
  }
}
```

This is an arbitrary use case, but there are many others. Especially when testing elements it is useful to know when rendering has occurred at least once 

Awaiting `updateComplete` is not ideal for this, since you might be awaiting the next update unnecessarily if rendering already occurred before. And the location where you are calling `updateComplete` might not have triggered a render, so it might be waiting forever for a render to occur.

It's easy to implement this yourself, but it would be nice to have something like this baked into `LitElement` as an idiomatic API:

```
class MyElement extends LitElement {
  constructor() {
    super();

    this.firstRendered = new Promise((resolve) => {
      this.firstRendered.resolve = resolve;
    });
  }

  firstUpdated() {
    this.firstRendered.resolve();
  }
}
```

I can work on a PR if this is something you are interested in supporting.

**Comment by justinfagnani** [comment]
At this point I would prefer to not add too many more features to LitElement/UpdatingElement. A mixin could easily provide this on top of UpdatingElement.

**Comment by gdbaldw** [comment]
This feature would improve time to first render for a toy app I'm developing to learn Lit-Element. With this feature, the app could render before executing (possibly even before downloading) any other modules. Nice to see this feature under consideration.

**Comment by justinfagnani** [comment]
@gdbaldw can you share some code that you think would be faster with this API?

**Comment by gdbaldw** [comment]
@justinfagnani yes. I developed  [Sudoku](https://github.com/gdbaldw/lit/blob/master/packages/client/sudoku-app/sudoku-board.ts) as a toy app. I'd hoped that by initializing the arrays at lines 42 and 48 to be Array(81).fill(null), an empty board would quickly render before the sudoku.js package downloaded and calculated an puzzle and solution. My hope brought me to see this feature request. You may see the working app (for now) at gdbaldw.netlify.com. In this case, time to render is not a practical issue, as this is purely an effort on my part to learn the art of the possible in this design space.

**Comment by Westbrook** [comment]
In this app, it looks to be the `import { makepuzzle, solvepuzzle } from "../web_modules/sudoku.js";` that is blocking your first render, not the render pipeline of `lit-element`. You _should_ get closer to what you're looking for here if you move that off of the critical/static path and request it lazily/dynamically, a la:

```
firstUpdated() {
    input('../web_modules/sudoku.js').then(module => {
        this.makepuzzle = module.makepuzzle;
        this.solvepuzzle = module.solvepuzzle;
        this.newpuzzle();
    });
}
```

**Comment by gdbaldw** [comment]
@Westbrook Nice, thank you! Had to change "input" to "import", mentioned for posterity. Works great.

**Comment by sorvell** [comment]
Closing since we haven't had other requests for this and it's pretty old.
