### ISSUE TITLE
Document authoring mixins in TypeScript

### ISSUE THREAD

**Issue by web-padawan** [lit/lit-element#829]
I have been looking for a small example of how to create a mixin, but there wasn't one.

So far I was able to come up with the following snippet:

```ts
import { LitElement, property } from 'lit-element';

type Constructor<T = object> = {
  new (...args: any[]): T;
  prototype: T;
};

export interface ReadonlyInterface {
  readonly: boolean;
}

export const ReadonlyMixin = <T extends Constructor<LitElement>>(
  base: T
): T & Constructor<ReadonlyInterface> => {
  class ReadonlyMixin extends base implements ReadonlyInterface {
    @property({ type: Boolean }) readonly: boolean = false;
  }
  return ReadonlyMixin;
};
```

Some things that I learned before I was able to make it work:

 - I started by tweaking the code from [model-viewer](https://github.com/GoogleWebComponents/model-viewer/tree/master/src/features) (which has mixins) 🤓 
- I found this [article](https://www.bryntum.com/blog/the-mixin-pattern-in-typescript-all-you-need-to-know/) useful to understand the `Constructor` type 🔖 
- I stumbled into microsoft/TypeScript#7342 and Microsoft/TypeScript#30355 (as well as related PR at GoogleWebComponents/model-viewer#761) 🤔 
- Finally, I found a working example at [stackoverflow](https://stackoverflow.com/a/43162485) 🙂 

Overall it was a bit challenging to figure that out 😅 So the example would help a lot.

@justinfagnani @cdata can you please confirm if the code snippet above is correct? Also, do you have any other guidelines about how mixins should be written in TypeScript?

**Comment by tpluscode** [comment]
here's how I have been defining my mixing:

```ts
import { LitElement, property } from 'lit-element';

type Constructor<T> = new (...args: any[]) => LitElement // or HTMLElement or other base class

interface ReadonlyInterface {
  readonly: boolean;
}

type ReturnConstructor = new (...args: any[]) => LitElement & ReadonlyInterface

export function ReadonlyMixin<B extends Constructor> (Base: B): B & ReturnConstructor {
    class Mixin extends Base implements ReadonlyInterface {
        @property({ type: Boolean }) readonly: boolean = false;
    }

    return Mixin
}
```

Looks similar but I wonder if the differences are significant. 🤔

**Comment by balloob** [comment]
TypeScript has [added support](https://github.com/microsoft/TypeScript/pull/13743) for the mixin pattern. However, it does not work with the constructor type that is exported by LitElement (and which is also the one referenced in the first post of this issue).

The TS compatible constructor type is

```ts
export type Constructor<T = {}> = new (...args: any[]) => T;
``` 

If you use that compatible constructor, you don't need to specify an output type, as TypeScript will be able to derive it.

For an example of this pattern, see https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/mixins/subscribe-mixin.ts

@justinfagnani, do you know why the constructor type of LitElement is the way it is?

**Comment by abdonrd** [comment]
I'm also interested on this! Right now I have:

```typescript
type Constructor<T> = new (...args: any[]) => T;

export const myMixin = () => <T extends Constructor<HTMLElement>>(
  baseElement: T
) => {
  class MyMixin extends baseElement {
    @property({ type: Object })
    public data: any;

    // ...
  }

  return MyMixin;
};
```

**Comment by web-padawan** [comment]
A follow-up question: how do we annotate  protected methods defined on the mixin, in a way that would make it overridable by the class extending that mixin?

So far I only found the workaround with a dumb clas: https://github.com/microsoft/TypeScript/issues/25163#issuecomment-507074489

Here is the code example illustrating what I want to accomplish:
https://github.com/vaadin/component-mixins/pull/7/commits/852bce2da2f2f0b44b7220727e3a258bbf068f2a#diff-0838769eda184397106cb15d225e1bdbR8-R21

@justinfagnani @rictic I would really appreciate any advice on how to handle this case.

**Comment by cdata** [comment]
@balloob I'm interested to know if you are able to build with `"declarations": true` in your tsconfig.json.

For `<model-viewer>`, we briefly landed a change that moved from specifying a separate interface to relying on similar inference, but we ran into a wall because it would not compile if you configure the compiler to generation declarations. See https://github.com/GoogleWebComponents/model-viewer/pull/761 for context.

**Comment by balloob** [comment]
@cdata correct, unable to build if we set `declarations` to `true` 😞.  We're building [an app](https://demo.home-assistant.io/) and not a lib, so don't need declarations.

**Comment by web-padawan** [comment]
Regarding the above question, here is my research regarding TS mixins & protected methods .

## Overview

The root problem is microsoft/TypeScript#17744 that is still unsolved.
See also "Related TS issues" below for more context.

These are 3 approaches that can be used for writing mixins that need to expose protected methods, so they can be overridden by the subclass with the `super` call.

## 1. Symbol approach

- Not using `protected` methods in the mixins

- Using `Symbol` as recommended by [Elix](https://component.kitchen/blog/posts/hiding-internal-framework-methods-and-properties-from-web-component-apis)

- Example: https://github.com/microsoft/TypeScript/issues/17744#issuecomment-431534647

### Pros

- Methods are truly protected (can't be called  from outside, e.g. by 3rd party code)

- Methods are "public" in terms of TS and can be annotated on the `interface`

- Explicit exports helping to make sure the consumers have compilation errors in case the new version was released an the internal API contracts of the protected methods have changed

- Methods are excluded from the DevTools console's auto-complete list (good for user)

- Symbols also avoid potential name conflicts if a component user wants to extend a custom element with their own methods.

### Cons

- Consumers have to import symbols if they need to override protected methods

- Jump to definition is not ideal (jumps to the place where `Symbol()` is created)

## 2. Dumb class approach

- Using `protected` methods in the mixins

- Using `abstract class SomeMixinClass extends LitElement` to "annotate" them

- Example: https://github.com/microsoft/TypeScript/issues/25163#issuecomment-507074489

### Pros

- No need to import anything (except the mixin itself) for the consumer component

- Methods are easy to access in the DevTools console (good for maintainer)

### Cons

- Both interface (for public API) and abstract class (for protected API) are needed

- The abstract class ends up in the JS output (as empty class with no methods)

- The mixin function needs to confusingly accept the argument with a type cast (instead of the actual expected class) in order to pick up the annotated protected methods from it: 

```ts
// with dumb class: confusing
<T extends Constructor<SlottedItemsClass>>(base: T)

// without dumb class: clean
<T extends Constructor<LitElement>>(base: T)
```

- Need for extra `super` check: `super._focus && super._focus()` - this is needed because the abstract classes mark methods using `_focus?()`, i.e. "possibly undefined"

- Methods can be only called in tests with `as any` workaround

- Jump to definition from the subclass goes to a dumb class

## 3. Public methods

- Keep methods `public`, add them on the `interface`

- Jump to definition works as expected

- Example: https://github.com/wikibus/Alcaeus/issues/33

## Pros

- No extra code needed (symbols / dumb classes)

## Cons

- TS users would get protected methods listed in the code completion

- Messing up `public` and `protected` API might need tweaks for tools

## Summary

Personally, I like symbols approach more because it's cleaner, and it's not about "fighting with how TypeScrip works". But I'm ok with using the `protected` methods, too.

## Related TS issues 

- https://github.com/microsoft/TypeScript/issues/17744

- https://github.com/microsoft/TypeScript/issues/25163#issuecomment-507062325

- https://github.com/microsoft/TypeScript/issues/17293#issuecomment-522491710

**Comment by trusktr** [comment]
It should be documented that if we use mixin classes, we must forgo the ability to publish them in a library with declaration files. https://github.com/microsoft/TypeScript/issues/35822

**Comment by web-padawan** [comment]
The new docs website has a dedicated page: 
https://lit.dev/docs/composition/mixins/#mixins-in-typescript

Closing as fixed.
