### ISSUE TITLE
Hybrid object (POJO <> customElement)

### ISSUE THREAD

**Issue by vdegenne** [lit/lit-element#869]
I thought I'd share this with you because I remember trying to use this design from Polymer 1, 2 but it was always a mess. Finally from Polymer 3 and then `LitElement` I can get closer from my expectation and I am very satisfied but there's still one caveat.

First let me show you what I try to do, I want to create an object that acts as a plain old object

```typescript
interface Planet {
  name: string,
  mass: number,
  satellites: string[]
}

const planet: Planet = {
  name: 'earth',
  mass: 5.97237e+24,
  satellites: ['moon']
}
```

**but also like a custom element**. In order to do that we can make a new `LitElement` element

```typescript
@customElement('planet-element')
class PlanetElement extends LitElement {
  @property({ type: String })
  public name: string = ''

  public mass: number = 0
  public satellites: string[] = []

  render () {
    return html`
    <h2>${this.name}</h2>
    `
  }
}
```

I already see 2 problems : 
- The properties need a default value if not optional _[1]_
- The auto-completion also includes the properties of `LitElement` _[2]_

To resolve _[1]_ default values have to be pass when the object is created (hence in the constructor) :

```typescript
// @ts-ignore
@customElement('planet-element')
class PlanetElement extends LitElement {
  @property({ type: String })
  public name: string = ''

  public mass: number = 0
  public satellites: string[] = []

  constructor (name: string, mass: number, satellites: string[]) {
    super()
    this.name = name
    this.mass = mass
    this.satellites = satellites
  }

  render () {
    return html`
    <h2>${this.name}</h2>
    `
  }
}
```

and because the constructor can't include parameters the decorator presents an exception which I, for now..., ignore using `// @ts-ignore`

To resolve _[2]_ I implement the interface

```typescript
// @ts-ignore
@customElement('planet-element')
class PlanetElement extends LitElement implements Planet {

  @property({ type: String })
  public name: string = ''

  public mass: number = 0
  public satellites: string[] = []

  constructor (name: string, mass: number, satellites: string[]) {
    super()
    this.name = name
    this.mass = mass
    this.satellites = satellites
  }

  render () {
    return html`
    <h2>${this.name}</h2>
    `
  }
}
```

We get somewhere, now we can type

```typescript
const myplanet = new PlanetElement('my little big planet', 12, ['b612'])

// it feels more like a plain object
myplanet.mass = 9999
myplanet.name = 'cool name' // rerender
```

And it acts like a custom element

```typescript
class SolarSystem extends LitElement {
  private planets: PlanetElement[] = []

  render () {
    return html`
      ${this.planets}
    `
  }
}
```

Thanks to `lit-html` this works. `lit-html` understands that the array is an array of `Planet` elements and stamps the appropriate template of each elements.

But still this is not near perfect for **3** reasons.

### 1. It's still a customElement

I expect the object to be a plain old one if for instance I type `JSON.stringify(myplanet)` it would include exposed properties of `LitElement` too.  
We could resolve it by creating this function in the custom element : 

```typescript
class PlanetElement ... {
  ...
  
  getPlainObject () {
    return <Planet>{
      name: this.name
      mass: this.mass
      satellites: this.satellites
    }
  }

  ...
}
```

Now `JSON.stringify(myplanet.getPlainObject())` works. But it gets even more cumbersome.

### 2. four parts to modify

When we need to add a property we have to modify four parts : in the interface, in the class properties, in the constructor, and in the `getPlainObject`.

### 3. Auto-completion

For the completion to only propose the properties of the POJO we need explicit specification :

```typescript
myplanet.<the auto-completion also includes `LitElement` properties>
(myplanet as Planet).<the auto-completion works well now>
```

---

I really wish there were a mechanism to achieve this. I wanted to expose this issue I am facing, I am sure this is not a pattern everyone's think about but I think it's worth considering.  
What would you say to someone that tries to seamlessly fusion a plain old JS object and a custom element ? Any suggestions, insights, ideas ?  

Thanks in advance.

**Comment by CaptainCodeman** [comment]
I normally have something like this:
```
@customElement('planet-element')
class PlanetElement extends LitElement {
  @property({ type: Object })
  public planet: Planet

  render () {
    return html`
    <h2>${this.planet.name}</h2>
    `
  }
}
```

**Comment by abraham** [comment]
`toJSON` should simplifier your JSON requirements.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON_behavior

**Comment by justinfagnani** [comment]
@vdegenne Can you back up a little and explain your motivation for wanting an element to also behave like a POJO? That might help us give recommendations.

**Comment by vdegenne** [comment]
@CaptainCodeman @justinfagnani Yes this is what I am falling back to but why couldn't a planet also be an element ?  
The way I see it web development becomes more and more modular and the browser is the stage for representing the data (objects). It's almost like our surroundings, objects have properties and if we could modify these properties the objects would have different shapes and reactions. If I "stamp my object in the browser" I'd expect it to be visually represented as I see it in term of visualisation and have the correct reactions to user interactions.  
I was surprised when I wrote `${myplanet}` to observe that `lit-html` "understood" it was a custom element and the screen displayed the intended rendering. I remember trying to do that in the very early versions of Polymer and was discouraged to see it was not working. But it looks like it becomes more and more easy to have this effect, that's why I wrote this post, not really a criticism about `LitElement` not being extensible enough but I just wanted to share some ideas of how to make this even more easy to approach.  

also @motss [suggested to remove the constructor and [to ignore the typescript errors about the initialization].
](https://polymer.slack.com/archives/C03PF4L4L/p1577118108142600?thread_ts=1577103307.137200&cid=C03PF4L4L)

**Comment by sorvell** [comment]
This is an interesting use case, but I'm not sure there's anything actionable that we'd want to do in the core LitElement library. Do you have any specific suggestions?

**Comment by vdegenne** [comment]
@sorvell Now that I think about it, there's nothing `LitElement` can do here. My complain seems to be more JavaScript and IDE oriented. I think I wanted some insight from the Polymer team!  
But because it's something I am always interested in I think I made some improvements about how to write this patter, here's how I do.

## Interface & Object

```typescript
// Planet interface
// only used for typescript cast
export interface Planet {
  name: string;
  mass: number;
  satellites: string[];
}

// Planet as an element.
// It's just a plain planet object
// extended with visual capabilities.
@customElement('planet-element')
export class PlanetElement extends LitElement {
  [key: string]: any;
  @property() name: string;
  mass: number;
  satellites: string[];

  protected render() {
    return html`<b>${this.name}</b>`;
  }

  toJSON() {
    const json = {} as any;
    for (const prop of Object.keys(this)) {
      if (prop.startsWith('__')) {
        json[prop.slice(2)] = this[prop];
      } else if (!prop.startsWith('_') && prop !== 'renderRoot') {
        json[prop] = this[prop];
      }
    }
    return json;
  }
}
```

To remove some TypeScript complains I had to set `strictPropertyInitialization` to `false` in my `tsconfig.json`.

Now I can use instant casting to simulate the plain object to places where I need to restrain the completion :

```typescript
class SolarSystem extends LitElement {
  protected planets: PlanetElement[] = [];

  protected addMarsToTheSystem() {
    let planetEl = new PlanetElement;
    let mars = planetEl as Planet;
    mars.name = 'Mars';
    mars.mass = 6.39e+23;
    mars.satellites = ['Phobos', 'Deimos'];
    this.planets.push(mars as PlanetElement);
  }

  logMarsInformation() {
    const mars = this.planets[this.planets.findIndex(
        planet => (planet as Planet).name === 'Mars')];
    console.log(JSON.stringify(mars));
  }

  protected render() {
    return html`${this.planets}`;
  }
}
```

**Comment by aomarks** [comment]
Closing as non-actionable for the Lit team.
