### ISSUE TITLE
[docs] Document static getStyles() for theme systems

### ISSUE THREAD

**Issue by justinfagnani** [lit/lit-element#877]
See https://github.com/Polymer/lit-element/pull/866

Apps and design systems that want to add additional styles to a component should override `getStyles()`. Previously they might have tried to override `finalize()`, but style gathering has been moved from there.

**Comment by ianes1978** [comment]
i don't know if is usefull for you problem i have made a little module 
[lit-css-global-scope](https://www.npmjs.com/package/lit-css-global-scope)
to import in the lit-element component the global style and preserve the shadowdom styles
