### ISSUE TITLE
Theming solution for LitElement

### ISSUE THREAD

**Issue by nicolejadeyee** [lit/lit-element#907]

**Comment by chase-moskal** [comment]
hello!

i just wanted to share that in my case, i found applying a shared css theme to many shadow-dom lit-element components was no sweat

using a decorator called [mixin-css](https://github.com/chase-moskal/authoritarian-client/blob/047e1d603c87b6fed0c9b9f50530c0e1d183948c/source/framework/mixin-css.ts#L4), and a couple helper functions, [theme-components](https://github.com/chase-moskal/authoritarian-client/blob/047e1d603c87b6fed0c9b9f50530c0e1d183948c/source/framework/theme-components.ts#L7) and [register-components](https://github.com/chase-moskal/authoritarian-client/blob/047e1d603c87b6fed0c9b9f50530c0e1d183948c/source/toolbox/register-components.ts#L4), i can easily [share a css theme across many components](https://github.com/chase-moskal/authoritarian-client/blob/047e1d603c87b6fed0c9b9f50530c0e1d183948c/source/startup/install-authoritarian.ts#L22) like this:

```ts
registerComponents(themeComponents(theme, components))
 //  ↑              ↑
 //  │              └——— apply the css theme to components
 //  │
 //  └—————————————————— register components via customElements.define
```

this pattern decouples each component from any particular theme, making themes for components easily swappable at a high level

&nbsp; :wave: chase

**Comment by motss** [comment]
IIUC, it basically achieves that using Constructible Stylesheets with fallback when needed.

**Comment by sorvell** [comment]
Closing in favor of lit/rfcs#10
