### ISSUE TITLE
Add documentation on unit testing

### ISSUE THREAD

**Issue by web-padawan** [lit/lit-element#913]
## Initiative / goal

While LitElement docs are clear, they don't provide any guide on how to test components.

People have to discover https://open-wc.org for some tools & recommendations.
But most of newbie developers are unlikely to find it quickly.

In contrast, Stencil docs have a [separate section](https://stenciljs.com/docs/testing-overview) on testing.

### Scope
- Improving docs to add testing guide

## Acceptance criteria and must have scope
- Developers should be able to setup unit tests  for their components with `karma` and `mocha` without having to search for any external documentation and resources.

**Comment by kevinpschaaf** [comment]
The new docs site now covers unit testing with recommendations on test frameworks and example configs: https://lit.dev/docs/tools/testing/
