### ISSUE TITLE
Docs for new property customization features

### ISSUE THREAD

**Issue by arthurevans** [lit/lit-element#932]
We added static getPropertyDescriptor to make it easier to customize how properties work.

To customize the property options, you can override static createProperty(name: PropertyKey, options: PropertyDeclaration) and change the options that you pass to the super call. To customize how property accessors work, you implement static getPropertyDescriptor(name: PropertyKey, key: string|symbol, options: PropertyDeclaration) and return a descriptor that does whatever you want in the getter/setter. In addition, we added getPropertyOptions(name: PropertyKey) to let people retrieve stored options to act on them, say, in other parts of the element lifecycle besides the setter (e.g. in updated).

### Scope

This doc is fairly advanced; it wouldn't go in the existing Properties section, but in some kind of advanced/cookbook section.

## Acceptance criteria and must have scope

Section describing property customization features, with example code.

**Comment by justinfagnani** [comment]
We have this for Lit 2 on lit.dev
